name: bar_clock
description: "A digital clock based on the look and feel of the HMI of a retro sports car."
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: DSEG
      fonts:
        - asset: third_party/DSEG7Modern-Bold.ttf
    - family: weather
      fonts:
        - asset: third_party/weathericons.ttf
